export const BasePartnerURL = 'http://192.168.0.7:8001/srishtishree/partner/';
export const BaseSharedUrl = 'http://192.168.0.7:8002/srishtishree/shared/';
export const BaseAdminUrl = 'http://192.168.0.7:8002/srishtishree/admin/';
export const BaseCustomerUrl = 'http://192.168.0.7:8000/srishtishree/customer/';

export const environment = {
  url: {
    login: 'login/',
    generateCode: 'generatecode/',
    country_url: 'get/countries/',
    state_url: 'get/states/',
    city_url: 'get/city/',
    district_url: 'get/districts/',
    signupUrl: 'signup/',
    store_list_url: 'store/get/',
    domainUrl: 'domain/',
    get_units_url: 'getunits/',
    document_uploadUrl: 'uploaddocument/',
    storeCreateUrl: 'store/create/',
    getBrandProductUrl: 'store/getproductsbybrand/',
    templateInfoUrl: 'template/info/',
    singleStoreUrl: 'store/getbyid/',
    getStoreStockUrl: 'store/getproducts/',
    tempateGetBYCatUrl: 'template/getbystorecategory/',
    brandCreateUrl: 'brand/create/',
    getUnitsUrl: 'get/units/',
    getCatUrlbytem: 'template/getcategory/',
    templateGetsubCatUrl: 'template/getsubcategory/',
    adminTemGetBrandUrl: 'template/getbrands/',
    getSingleProductUrl: 'store/getsingleproduct/',
    UPDATE_STORE_URL: 'store/update/',
    getVariantUrl: 'template/getvariantbytype/',
    createProductUrl: 'store/createproduct/',
    partnerStockUpdateUrl: 'store/updatestock/',
    ProductEditUrl: 'store/editproduct/',
    CreateUserUrl: 'create/',
    getEntityTypeUrl: 'get/entitytype/',
    PosShiftStartUrl: 'pos/shiftbegin/',
    shiftEndUrl: 'pos/shiftend/',
    customerGetUrl: 'pos/getcustomer/',
    customerRegistrationUrl: 'pos/customerregistration/',
    getRolesUrl: 'get/entitytypeapplicablerole/',
    getuserlistUrl: 'userlist/',
    serchProductUrl: 'pos/searchproduct/',
    productBookingUrl: 'pos/booking/',
    bookingInitUrl: 'pos/getbooking/',
    holdBillUrl: 'pos/getholdbills/',
    updateUserStatus: 'update/userstatus/',
    singleUserDetailsUrl: 'getbyid/',
    VoidOrderUrl: 'pos/updateorder/',
    removeItemUrl: 'pos/removeitem/',
    PaymentInitialUrl: 'pos/getpayment/',
    PaidPaymentUrl: 'pos/payment/',
    GetPaymentSummery: 'pos/shiftsummary/',
    TransferAmountUr: 'pos/transfercash/',
    WishListGetUrl: 'requisition/getallwishlist/',
    GetCompleteOrderHistoryUrl: 'pos/getorders/',
    OrderDetailHistoryUrl: 'pos/getorderdetails/',
    getOrderDetailsUrl: 'orders/bagdetails/',
    updateOrderDetailsUrl: 'orders/updatebagstatus/',
    getAllOrderUrl: 'orders/getactive/',
    searchProductUrlForCust: 'store/searchinventory/',
    SerchProductListUrl: 'requisition/productlist/',
    CreateRequsitionUrl: 'requisition/createwishlist/',
    GetWishListByIdUrl: 'requisition/wishlistbyid/',
    RqqusitionUpdateUrl: 'requisition/updatestatus/',
    UpdateBagStatusUrl: 'orders/updatebagstatus/',
    GetStockFullfillmentUrl: 'requisition/getrequisition/',
    ChangePasswordUrl: 'resetpassword/',
    ForgotPasswordUrl: 'forgetpassword/',
    GenerateOtpUrl: 'generateotp/',
    FulFillmentCreateUrl: 'requisition/createfulfilment/',
    GetFullfilmentByIdUrl: 'requisition/fulfilmentbyid/',
    reqCreateProductUrl: 'requisition/createupdateproduct/',
    returnProductUrl: 'pos/getreturn/',
    billReturnUrl: 'pos/return/',
    onlinePaymentUrl: 'pos/onlinepayment/',
    goodRecivedUrl: 'requisition/storerecieveproduct/',
    recived_listUrl: 'requisition/goodsreceivedlist/',
    getreturnUrl: 'pos/getreturns/',
    returnDetailUrl: 'pos/getreturndetails/',
    reciveGoodPosUrl: 'pos/returnstatusupdate/',
    getSimilarProducetUrl: 'store/groupedproducts/',
    getVersionUrl: 'fetchappversion/',
  },
  S3_Crad: {
    
  },
  app_Version: {
    versionCode: '1.0.0',
  },
};
