import {StoreState} from '../../models/reduxModel';

const InitialState: StoreState = {
  error: {
    error: undefined,
  },
  loading: {
    count: 0,
    message: '',
  },
  user: {
    user_detail: undefined,
  },
  domain: {
    cities: [],
    countries: [],
    states: [],
    districts: [],
  },
  store: {
    storeList: [],
    storeCategories: [],
    unit: [],
    storeStock: [],
    singleStore: undefined,
    brandAddDone: false,
    stockAddDone: false,
    templates: [],
    templateInfo: undefined,
    productBrands: [],
    productCategories: [],
    productSubCategories: [],
    templateList: [],
    units: [],
    singleProductDetail: undefined,
    varients: [],
    txnTypes: [],
    updateStockDone: false,
    updatingDone: false,
    qr: '',
    qr_flag: false,
    productEditDone: false,
    similar_product: [],
  },
  location: null,
  usermanagement: {
    entity_type_main: [],
    role_type_main: [],
    userList: [],
    singleUserDetails: undefined,
  },
  pos: {
    new_customer: false,
    search_flag: false,
    searchProduct: undefined,
    order_details: undefined,
    frequents: [],
    holdbill: [],
    payment_mode: [],
    payment_due: undefined,
    paid_Payment: false,
    returnAmount: undefined,
    payment_summery: undefined,
    PreviousOrder: [],
    total_count: undefined,
    orderHistoryDetail: undefined,
    price_breakup: [],
    all_return_details: undefined,
    bill_return_refund: undefined,
    refund_list: {
      returns: [],
      total_count: 0,
    },
    return_det: undefined,
  },
  wish_list: {
    wishListLists: [],
    no_wishlist: [],
    product_list: [],
    total_count: undefined,
    wishlist_detail: undefined,
    GoodRecived: undefined,
    total: undefined,
  },
  order: {
    OrderList: [],
    SingleOrder: undefined,
    bagStatus: [],
    Payment_type: [],
    active_order: 0,
    conversation: [],
    orderStatus: [],
  },
  stock: {
    requisitionList: [],
    requsition_detail: undefined,
    total: undefined,
  },
};
export default InitialState;
